.TH GET_HOLIDAYS 1 "27 August 2019"
.SH NAME
get-holidays - Get Holidays for country entered
.SH SYNOPSIS
\fBget-holidays\fP \fI<year>\fP [country]
.SH DESCRIPTION 
The country name needs to be in english and without any typo to be recognized. However, the argument collector is not case-sensitive(both Belgium, BELGIUM & bElGiUm works).
.SS Options
.TP
\fB[country]\fP 
Required. Must be in english and correctly spelled. Not case-sensitive.
.TP
\fB<year>\fP
Optionnal. If not provided, uses the current year.
.SH AUTHOR
Lindsay Vannebenne
.UR https://github.com/LVannebenne/get-holidays-CLI
.UE

